using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace RBX_Alt_Manager.Classes
{
    internal class Batch
    {
        /// <summary>
        /// Combines multiple requests into one using Roblox's API
        /// <para>
        /// The point of this class is to combine multiple requests into 1 request
        /// using Roblox's "multiget-place-details" and the thumbnail batch API by
        /// opening a small 50 millisecond timeframe to request multiple thumbnails
        /// for multiple games in separate code sections.
        /// </para>
        /// </summary>

        private static readonly RestClient ThumbnailAPI = new RestClient("https://thumbnails.roblox.com/");
        private static readonly RestClient GamesAPI = new RestClient("https://games.roblox.com/");

        private static readonly object PlaceTaskLock = new object();
        private static readonly object BatchTaskLock = new object();

        private static Task<JArray> CurrentBatchTask;
        private static Task CurrentPlaceTask;

        private static readonly List<object> PendingBatch = new List<object>();
        private static readonly List<long> PendingPlace = new List<long>();

        private static readonly Dictionary<long, long> PlaceUniversePair = new Dictionary<long, long>();
        public static readonly Dictionary<long, GameDetails> PlaceDetails = new Dictionary<long, GameDetails>();

        /// <summary>
        /// Get an image for the specified Asset
        /// </summary>
        /// <param name="AssetId">Asset ID</param>
        /// <param name="Type">Image Type (Avatar, AvatarHeadShot, GameIcon, BadgeIcon, GameThumbnail, GamePass, Asset, BundleThumbnail, Outfit, GroupIcon, DeveloperProduct, AutoGeneratedAsset, AvatarBust, PlaceIcon, AutoGeneratedGameIcon, ForceAutoGeneratedGameIcon)</param>
        /// <param name="Size">Image Size</param>
        /// <param name="Format">Image Format (png/jpeg)</param>
        /// <returns>A string containing the Image Url</returns>
        public static async Task<string> GetImage(long AssetId, string Type, string Size = "150x150", string Format = null)
        {
            if (AccountManager.General.Get<bool>("DisableImages"))
                return string.Empty;

            lock (BatchTaskLock)
            {
                if (CurrentBatchTask == null || CurrentBatchTask.IsCompleted || CurrentBatchTask.IsCanceled)
                {
                    CurrentBatchTask?.Dispose();
                    CurrentBatchTask = Task.Run(DoBatchRequest);
                }
            }

            PendingBatch.Add(new
            {
                requestId = $"{AssetId}:undefined:{Type}:{Size}:{Format}:regular",
                type = Type,
                targetId = AssetId,
                size = Size,
                format = Format ?? null
            });

            return await CurrentBatchTask.ContinueWith(task =>
            {
                if (CurrentBatchTask.IsFaulted)
                    throw CurrentBatchTask.Exception;

                return task.Result?.Where(x => x["errorCode"].Value<int>() == 0 && (x["targetId"]?.Value<long>() ?? 0) == AssetId).FirstOrDefault()?["imageUrl"]?.Value<string>() ?? "UNK";
            });
        }

        /// <summary>
        /// Get a game's name, resolved from its Place ID
        /// </summary>
        /// <param name="PlaceId">The PlaceId of the target game</param>
        /// <returns></returns>
        public static async Task<string> GetGameName(long PlaceId)
        {
            if (PlaceId <= 0) return string.Empty;

            if (PlaceDetails.TryGetValue(PlaceId, out GameDetails Cached)) return Cached.name;

            lock (PlaceTaskLock)
            {
                if (CurrentPlaceTask == null || CurrentPlaceTask.IsCompleted || CurrentPlaceTask.IsCanceled)
                {
                    CurrentPlaceTask?.Dispose();
                    CurrentPlaceTask = Task.Run(DoPlaceRequest);
                }
            }

            PendingPlace.Add(PlaceId);

            await CurrentPlaceTask;

            if (CurrentPlaceTask.IsFaulted)
                throw CurrentPlaceTask.Exception;

            return PlaceDetails.TryGetValue(PlaceId, out GameDetails Details) ? Details.name : string.Empty;
        }

        /// <summary>
        /// Get the current/max player count of the specific server (game instance) a
        /// PlaceId+JobId pair is running in, using Roblox's public server list API.
        /// </summary>
        /// <param name="PlaceId">The PlaceId the server belongs to</param>
        /// <param name="JobId">The JobId (server instance id) to look up</param>
        /// <returns>A tuple of (Playing, MaxPlayers), or (-1, -1) if not found/failed</returns>
        public static async Task<(int Playing, int MaxPlayers)> GetServerInfo(long PlaceId, string JobId)
        {
            if (PlaceId <= 0 || string.IsNullOrEmpty(JobId)) return (-1, -1);

            // The servers endpoint is keyed by PlaceId directly, not UniverseId, so no
            // extra multiget-place-details round trip is needed here.
            string Cursor = "";

            // Cap the number of pages walked so a huge/looping server list (or a server
            // that's fallen off page 1 because a lot of servers were created since) can't
            // spin this forever - 10 pages * 100 servers is generous for finding one match.
            for (int Page = 0; Page < 10; Page++)
            {
                var Request = new RestRequest($"v1/games/{PlaceId}/servers/Public?sortOrder=Asc&limit=100{(string.IsNullOrEmpty(Cursor) ? "" : $"&cursor={Uri.EscapeDataString(Cursor)}")}");

                Request.AddCookie(".ROBLOSECURITY", AccountManager.LastValidAccount?.SecurityToken, "/", ".roblox.com");

                RestResponse Response = await GamesAPI.ExecuteAsync(Request);

                if (!Response.IsSuccessful)
                {
                    Program.Logger.Warn($"{Response.StatusCode} servers request failed for PlaceId {PlaceId}\nError: {Response.ErrorMessage}\nContent: {Response.Content}");
                    return (-1, -1);
                }

                JObject Body = JObject.Parse(Response.Content);
                JArray Servers = Body["data"]?.Value<JArray>();

                if (Servers != null)
                    foreach (JToken Server in Servers)
                        if (string.Equals(Server["id"]?.Value<string>(), JobId, StringComparison.OrdinalIgnoreCase))
                            return (Server["playing"]?.Value<int>() ?? -1, Server["maxPlayers"]?.Value<int>() ?? -1);

                Cursor = Body["nextPageCursor"]?.Value<string>();

                if (string.IsNullOrEmpty(Cursor)) break;
            }

            return (-1, -1);
        }

        /// <summary>
        /// Get a game's icon
        /// </summary>
        /// <param name="PlaceId">The PlaceId of the target game</param>
        /// <returns></returns>
        public static async Task<string> GetGameIcon(long PlaceId)
        {
            if (AccountManager.General.Get<bool>("DisableImages"))
                return string.Empty;

            lock (PlaceTaskLock)
            {
                if (CurrentPlaceTask == null || CurrentPlaceTask.IsCompleted || CurrentPlaceTask.IsCanceled)
                {
                    CurrentPlaceTask?.Dispose();
                    CurrentPlaceTask = Task.Run(DoPlaceRequest);
                }
            }

            PendingPlace.Add(PlaceId);

            await CurrentPlaceTask;

            if (CurrentPlaceTask.IsFaulted)
                throw CurrentPlaceTask.Exception;

            if (!PlaceUniversePair.TryGetValue(PlaceId, out long UniverseId)) return await GetAssetImage(PlaceId);

            return await GetImage(UniverseId, "GameIcon", "512x512", "png");
        }

        private static async Task<JArray> DoBatchRequest()
        {
            await Task.Delay(50);

            JArray ReturnArray = new JArray();

            while (PendingBatch.Count > 0)
            {
                List<object> Pending = new List<object>();

                Pending.AddRange(PendingBatch.GetRange(0, Math.Min(PendingBatch.Count, 100)));
                PendingBatch.RemoveRange(0, Math.Min(PendingBatch.Count, 100));

                var Request = new RestRequest("v1/batch", Method.Post);
                Request.AddJsonBody(Pending.ToArray());

                var Response = await ThumbnailAPI.ExecuteAsync(Request);

                if (!Response.IsSuccessful)
                    throw new HttpException($"{Response.StatusCode} Batch request failed\nBody: {Pending.ToArray()}\nError: {Response.ErrorMessage}");

                JArray Data = JObject.Parse(Response.Content)?["data"]?.Value<JArray>();

                if (Data != null)
                    foreach (JToken Token in Data)
                        ReturnArray.Add(Token);
            }

            return ReturnArray;
        }

        private static async Task DoPlaceRequest()
        {
            await Task.Delay(50);

            while (AccountManager.LastValidAccount == null)
                await Task.Delay(80);

            while (PendingPlace.Count > 0)
            {
                List<long> Pending = new List<long>();

                Pending.AddRange(PendingPlace.GetRange(0, Math.Min(PendingPlace.Count, 50)));
                PendingPlace.RemoveRange(0, Math.Min(PendingPlace.Count, 50));

                foreach (long PlaceId in new List<long>(Pending))
                    if (PlaceDetails.ContainsKey(PlaceId))
                        Pending.Remove(PlaceId);

                if (Pending.Count == 0) continue;

                var Request = new RestRequest($"v1/games/multiget-place-details?placeIds={string.Join("&placeIds=", Pending.ToArray())}");

                Request.AddCookie(".ROBLOSECURITY", AccountManager.LastValidAccount?.SecurityToken, "/", ".roblox.com");

                RestResponse DetailsResponse = await GamesAPI.ExecuteAsync(Request);

                if (DetailsResponse.IsSuccessful)
                {
                    GameDetails[] Games = JsonConvert.DeserializeObject<GameDetails[]>(DetailsResponse.Content); // JArray Places = JArray.Parse(DetailsResponse.Content);

                    foreach (GameDetails game in Games)
                    {
                        long PlaceId = game.placeId; // ["placeId"].Value<long>();

                        if (!PlaceDetails.ContainsKey(PlaceId))
                            PlaceDetails.Add(PlaceId, game);

                        if (!PlaceUniversePair.ContainsKey(PlaceId))
                            PlaceUniversePair.Add(PlaceId, game.universeId); // game["universeId"].Value<long
                    }
                }
                else
                    Program.Logger.Warn($"{DetailsResponse.StatusCode} multiget-place-details request failed\nBody: {string.Join(",", Pending)}\nError: {DetailsResponse.ErrorMessage}\nContent: {DetailsResponse.Content}");
            }
        }

        private static async Task<string> GetAssetImage(long AssetId) // bad fallback method
        {
            if (AccountManager.General.Get<bool>("DisableImages"))
                return string.Empty;

            var Request = new RestRequest($"v1/assets?assetIds={AssetId}&returnPolicy=PlaceHolder&size=150x150&format=Png&isCircular=false");

            Request.AddCookie(".ROBLOSECURITY", AccountManager.LastValidAccount?.SecurityToken, "/", ".roblox.com");

            var Response = await ThumbnailAPI.ExecuteAsync(Request);

            if (!Response.IsSuccessful) {
                Program.Logger.Error($"{Response.StatusCode} Asset Image request failed\nError: {Response.ErrorMessage}\nContent: {Response.Content}");
                return "UNK"; // throw new HttpException($"{Response.StatusCode} Asset Image request failed\nError: {Response.ErrorMessage}");
                              }

            JArray Data = JObject.Parse(Response.Content)?["data"]?.Value<JArray>();

            if (Data != null && Data.Count > 0)
                return Data[0]?["imageUrl"]?.Value<string>();

            return "UNK";
        }
    }
}