using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;

namespace RBX_Alt_Manager.Classes
{
    internal class Batch
    {
        /// <summary>
        /// Combines multiple requests into one using Roblox's API
        /// <para>
        /// The point of this class is to combine multiple requests into 1 request
        /// using Roblox's "multiget-place-details" and the thumbnail batch API by
        /// opening a small 50 millisecond timeframe to request multiple thumbnails
        /// for multiple games in separate code sections.
        /// </para>
        /// </summary>

        private static readonly RestClient ThumbnailAPI = new RestClient("https://thumbnails.roblox.com/");
        private static readonly RestClient GamesAPI = new RestClient("https://games.roblox.com/");

        private static readonly object PlaceTaskLock = new object();
        private static readonly object BatchTaskLock = new object();

        private static Task<JArray> CurrentBatchTask;
        private static Task CurrentPlaceTask;

        private static readonly List<object> PendingBatch = new List<object>();
        private static readonly List<long> PendingPlace = new List<long>();

        private static readonly Dictionary<long, long> PlaceUniversePair = new Dictionary<long, long>();
        public static readonly Dictionary<long, GameDetails> PlaceDetails = new Dictionary<long, GameDetails>();

        // Roblox rate-limits the servers/Public endpoint hard, and it's shared across every
        // account this app is watching - if 2+ accounts each walk their own 40-page server
        // search concurrently, they trip each other's rate limit almost immediately and can
        // end up retrying forever. This semaphore forces every GetServerInfo call (regardless
        // of which account/PlaceId it's for) through one at a time with spacing between them,
        // so the whole app makes one steady stream of requests instead of several competing
        // bursts.
        private static readonly SemaphoreSlim ServersRequestGate = new SemaphoreSlim(1, 1);

        // Both multiget-place-details and servers/Public work fine anonymously - a cookie only
        // buys a higher rate limit. Accounts that showed up through Nexus (executor-run
        // Nexus.lua) were auto-added with just a Username/UserID and no cookie, so
        // LastValidAccount.SecurityToken is null for them, and AddCookie with a null value
        // throws "The 'Value'='<null>' part of the cookie is invalid" - which is what left the
        // Map and Players columns permanently blank. Send the cookie only when there actually
        // is one, otherwise make the request anonymously.
        private static void AddAuthCookie(RestRequest Request)
        {
            string Token = AccountManager.LastValidAccount?.SecurityToken;

            if (!string.IsNullOrEmpty(Token))
                Request.AddCookie(".ROBLOSECURITY", Token, "/", ".roblox.com");
        }

        // Every server seen while walking a PlaceId's list gets cached here (not just the one
        // JobId that was being looked for) - a full walk for one account's lookup ends up
        // pre-answering every other account sitting in the same game for free, and even a
        // second lookup for the same account/JobId a minute later can often be answered without
        // any request at all. Keyed by (PlaceId, JobId); each entry expires after a short TTL
        // so periodic polling doesn't just show ever-more-stale numbers.
        private static readonly Dictionary<(long PlaceId, string JobId), (int Playing, int MaxPlayers, DateTime CachedAt)> ServerInfoCache = new Dictionary<(long, string), (int, int, DateTime)>();
        private static readonly object ServerInfoCacheLock = new object();
        private static readonly TimeSpan ServerInfoCacheTtl = TimeSpan.FromSeconds(45);

        /// <summary>
        /// Get an image for the specified Asset
        /// </summary>
        /// <param name="AssetId">Asset ID</param>
        /// <param name="Type">Image Type (Avatar, AvatarHeadShot, GameIcon, BadgeIcon, GameThumbnail, GamePass, Asset, BundleThumbnail, Outfit, GroupIcon, DeveloperProduct, AutoGeneratedAsset, AvatarBust, PlaceIcon, AutoGeneratedGameIcon, ForceAutoGeneratedGameIcon)</param>
        /// <param name="Size">Image Size</param>
        /// <param name="Format">Image Format (png/jpeg)</param>
        /// <returns>A string containing the Image Url</returns>
        public static async Task<string> GetImage(long AssetId, string Type, string Size = "150x150", string Format = null)
        {
            if (AccountManager.General.Get<bool>("DisableImages"))
                return string.Empty;

            lock (BatchTaskLock)
            {
                if (CurrentBatchTask == null || CurrentBatchTask.IsCompleted || CurrentBatchTask.IsCanceled)
                {
                    CurrentBatchTask?.Dispose();
                    CurrentBatchTask = Task.Run(DoBatchRequest);
                }
            }

            PendingBatch.Add(new
            {
                requestId = $"{AssetId}:undefined:{Type}:{Size}:{Format}:regular",
                type = Type,
                targetId = AssetId,
                size = Size,
                format = Format ?? null
            });

            return await CurrentBatchTask.ContinueWith(task =>
            {
                if (CurrentBatchTask.IsFaulted)
                    throw CurrentBatchTask.Exception;

                return task.Result?.Where(x => x["errorCode"].Value<int>() == 0 && (x["targetId"]?.Value<long>() ?? 0) == AssetId).FirstOrDefault()?["imageUrl"]?.Value<string>() ?? "UNK";
            });
        }

        /// <summary>
        /// Get a game's name, resolved from its Place ID
        /// </summary>
        /// <param name="PlaceId">The PlaceId of the target game</param>
        /// <returns></returns>
        public static async Task<string> GetGameName(long PlaceId)
        {
            if (PlaceId <= 0) return string.Empty;

            if (PlaceDetails.TryGetValue(PlaceId, out GameDetails Cached)) return Cached.name;

            // Queue the PlaceId BEFORE starting the batch task - DoPlaceRequest drains
            // PendingPlace and exits as soon as it's empty, so adding afterwards could miss the
            // window entirely and leave the game name (the grid's Map column) unresolved.
            PendingPlace.Add(PlaceId);

            lock (PlaceTaskLock)
            {
                if (CurrentPlaceTask == null || CurrentPlaceTask.IsCompleted || CurrentPlaceTask.IsCanceled)
                {
                    CurrentPlaceTask?.Dispose();
                    CurrentPlaceTask = Task.Run(DoPlaceRequest);
                }
            }

            await CurrentPlaceTask;

            if (CurrentPlaceTask.IsFaulted)
                throw CurrentPlaceTask.Exception;

            return PlaceDetails.TryGetValue(PlaceId, out GameDetails Details) ? Details.name : string.Empty;
        }

        /// <summary>
        /// Get the current/max player count of the specific server (game instance) a
        /// PlaceId+JobId pair is running in, using Roblox's public server list API.
        /// </summary>
        /// <param name="PlaceId">The PlaceId the server belongs to</param>
        /// <param name="JobId">The JobId (server instance id) to look up</param>
        /// <returns>A tuple of (Playing, MaxPlayers), or (-1, -1) if not found/failed</returns>
        public static async Task<(int Playing, int MaxPlayers)> GetServerInfo(long PlaceId, string JobId)
        {
            if (PlaceId <= 0 || string.IsNullOrEmpty(JobId)) return (-1, -1);

            var CacheKey = (PlaceId, JobId);

            // Cache hit - either this exact JobId was looked up recently, or another account's
            // walk of this same PlaceId happened to pass through it. Either way, skip the
            // network entirely.
            lock (ServerInfoCacheLock)
            {
                if (ServerInfoCache.TryGetValue(CacheKey, out var Cached) && DateTime.UtcNow - Cached.CachedAt < ServerInfoCacheTtl)
                    return (Cached.Playing, Cached.MaxPlayers);
            }

            // Serialize against every other in-flight GetServerInfo call (see ServersRequestGate)
            // so multiple watched accounts don't each independently hammer this endpoint and
            // trip Roblox's rate limit off of each other.
            await ServersRequestGate.WaitAsync();

            try
            {
                // Re-check the cache after acquiring the gate - another account's lookup may
                // have just finished a full walk (and populated this JobId) while this call was
                // waiting its turn, in which case there's nothing left to do.
                lock (ServerInfoCacheLock)
                {
                    if (ServerInfoCache.TryGetValue(CacheKey, out var Cached) && DateTime.UtcNow - Cached.CachedAt < ServerInfoCacheTtl)
                        return (Cached.Playing, Cached.MaxPlayers);
                }

                // The servers endpoint is keyed by PlaceId directly, not UniverseId, so no
                // extra multiget-place-details round trip is needed here.
                string Cursor = "";
                int RateLimitRetries = 0;
                (int Playing, int MaxPlayers) Found = (-1, -1);

                // Popular games can have thousands of concurrent servers (e.g. 500+ for a game
                // with ~14000 concurrent players at 28/server) - a low page cap can miss a real
                // match just because it's sorted further back, especially with sortOrder=Asc
                // where many servers tie on low player counts. 40 pages * 100 = 4000 servers
                // covers almost any game while still bounding the worst case.
                for (int Page = 0; Page < 40; Page++)
                {
                    var Request = new RestRequest($"v1/games/{PlaceId}/servers/Public?sortOrder=Asc&limit=100{(string.IsNullOrEmpty(Cursor) ? "" : $"&cursor={Uri.EscapeDataString(Cursor)}")}");

                    AddAuthCookie(Request);

                    RestResponse Response = await GamesAPI.ExecuteAsync(Request);

                    // 429s are common on this endpoint once a few pages have been walked in
                    // quick succession - back off and retry a bounded number of times instead of
                    // either giving up immediately or (the previous bug) retrying the same page
                    // forever, which just added to the rate-limit pressure instead of easing it.
                    if ((int)Response.StatusCode == 429)
                    {
                        RateLimitRetries++;

                        if (RateLimitRetries > 5)
                        {
                            Program.Logger.Warn($"Gave up walking servers for PlaceId {PlaceId} after repeated rate limiting");
                            return Found.Playing >= 0 ? Found : (-1, -1);
                        }

                        Program.Logger.Warn($"Rate limited walking servers for PlaceId {PlaceId}, backing off (page {Page}, attempt {RateLimitRetries})");
                        await Task.Delay(1000 * RateLimitRetries);
                        Page--;
                        continue;
                    }

                    RateLimitRetries = 0;

                    if (!Response.IsSuccessful)
                    {
                        Program.Logger.Warn($"{Response.StatusCode} servers request failed for PlaceId {PlaceId}\nError: {Response.ErrorMessage}\nContent: {Response.Content}");
                        return Found.Playing >= 0 ? Found : (-1, -1);
                    }

                    JObject Body = JObject.Parse(Response.Content);
                    JArray Servers = Body["data"]?.Value<JArray>();

                    // Cache every server on this page, not just the one being searched for -
                    // this is what lets a second account in the same game (or a repeat poll of
                    // this same JobId shortly after) skip the network entirely.
                    if (Servers != null)
                    {
                        DateTime Now = DateTime.UtcNow;

                        lock (ServerInfoCacheLock)
                        {
                            foreach (JToken Server in Servers)
                            {
                                string Id = Server["id"]?.Value<string>();

                                if (string.IsNullOrEmpty(Id)) continue;

                                int ServerPlaying = Server["playing"]?.Value<int>() ?? -1;
                                int ServerMax = Server["maxPlayers"]?.Value<int>() ?? -1;

                                ServerInfoCache[(PlaceId, Id)] = (ServerPlaying, ServerMax, Now);

                                if (string.Equals(Id, JobId, StringComparison.OrdinalIgnoreCase))
                                    Found = (ServerPlaying, ServerMax);
                            }
                        }

                        if (Found.Playing >= 0) return Found;
                    }

                    Cursor = Body["nextPageCursor"]?.Value<string>();

                    if (string.IsNullOrEmpty(Cursor)) break;

                    // Small spacing between page requests to avoid tripping the rate limit in
                    // the first place on games with a lot of servers to walk through.
                    await Task.Delay(300);
                }

                // Not found after walking every page - most commonly means the target JobId is
                // a private/reserved server (never listed under servers/Public at all) or the
                // lookup ran before Roblox's own listing had indexed the new server yet. Logged
                // because this previously failed completely silently, indistinguishable from a
                // real bug.
                Program.Logger.Warn($"No matching public server found for PlaceId {PlaceId} JobId {JobId}");
                return (-1, -1);
            }
            finally
            {
                ServersRequestGate.Release();
            }
        }

        /// <summary>
        /// Get a game's icon
        /// </summary>
        /// <param name="PlaceId">The PlaceId of the target game</param>
        /// <returns></returns>
        public static async Task<string> GetGameIcon(long PlaceId)
        {
            if (AccountManager.General.Get<bool>("DisableImages"))
                return string.Empty;

            lock (PlaceTaskLock)
            {
                if (CurrentPlaceTask == null || CurrentPlaceTask.IsCompleted || CurrentPlaceTask.IsCanceled)
                {
                    CurrentPlaceTask?.Dispose();
                    CurrentPlaceTask = Task.Run(DoPlaceRequest);
                }
            }

            PendingPlace.Add(PlaceId);

            await CurrentPlaceTask;

            if (CurrentPlaceTask.IsFaulted)
                throw CurrentPlaceTask.Exception;

            if (!PlaceUniversePair.TryGetValue(PlaceId, out long UniverseId)) return await GetAssetImage(PlaceId);

            return await GetImage(UniverseId, "GameIcon", "512x512", "png");
        }

        private static async Task<JArray> DoBatchRequest()
        {
            await Task.Delay(50);

            JArray ReturnArray = new JArray();

            while (PendingBatch.Count > 0)
            {
                List<object> Pending = new List<object>();

                Pending.AddRange(PendingBatch.GetRange(0, Math.Min(PendingBatch.Count, 100)));
                PendingBatch.RemoveRange(0, Math.Min(PendingBatch.Count, 100));

                var Request = new RestRequest("v1/batch", Method.Post);
                Request.AddJsonBody(Pending.ToArray());

                var Response = await ThumbnailAPI.ExecuteAsync(Request);

                if (!Response.IsSuccessful)
                    throw new HttpException($"{Response.StatusCode} Batch request failed\nBody: {Pending.ToArray()}\nError: {Response.ErrorMessage}");

                JArray Data = JObject.Parse(Response.Content)?["data"]?.Value<JArray>();

                if (Data != null)
                    foreach (JToken Token in Data)
                        ReturnArray.Add(Token);
            }

            return ReturnArray;
        }

        private static async Task DoPlaceRequest()
        {
            await Task.Delay(50);

            while (PendingPlace.Count > 0)
            {
                List<long> Pending = new List<long>();

                Pending.AddRange(PendingPlace.GetRange(0, Math.Min(PendingPlace.Count, 50)));
                PendingPlace.RemoveRange(0, Math.Min(PendingPlace.Count, 50));

                foreach (long PlaceId in new List<long>(Pending))
                    if (PlaceDetails.ContainsKey(PlaceId))
                        Pending.Remove(PlaceId);

                if (Pending.Count == 0) continue;

                var Request = new RestRequest($"v1/games/multiget-place-details?placeIds={string.Join("&placeIds=", Pending.ToArray())}");

                AddAuthCookie(Request);

                RestResponse DetailsResponse = await GamesAPI.ExecuteAsync(Request);

                if (DetailsResponse.IsSuccessful)
                {
                    GameDetails[] Games = JsonConvert.DeserializeObject<GameDetails[]>(DetailsResponse.Content); // JArray Places = JArray.Parse(DetailsResponse.Content);

                    foreach (GameDetails game in Games)
                    {
                        long PlaceId = game.placeId; // ["placeId"].Value<long>();

                        if (!PlaceDetails.ContainsKey(PlaceId))
                            PlaceDetails.Add(PlaceId, game);

                        if (!PlaceUniversePair.ContainsKey(PlaceId))
                            PlaceUniversePair.Add(PlaceId, game.universeId); // game["universeId"].Value<long
                    }
                }
                else
                    Program.Logger.Warn($"{DetailsResponse.StatusCode} multiget-place-details request failed\nBody: {string.Join(",", Pending)}\nError: {DetailsResponse.ErrorMessage}\nContent: {DetailsResponse.Content}");
            }
        }

        private static async Task<string> GetAssetImage(long AssetId) // bad fallback method
        {
            if (AccountManager.General.Get<bool>("DisableImages"))
                return string.Empty;

            var Request = new RestRequest($"v1/assets?assetIds={AssetId}&returnPolicy=PlaceHolder&size=150x150&format=Png&isCircular=false");

            Request.AddCookie(".ROBLOSECURITY", AccountManager.LastValidAccount?.SecurityToken, "/", ".roblox.com");

            var Response = await ThumbnailAPI.ExecuteAsync(Request);

            if (!Response.IsSuccessful) {
                Program.Logger.Error($"{Response.StatusCode} Asset Image request failed\nError: {Response.ErrorMessage}\nContent: {Response.Content}");
                return "UNK"; // throw new HttpException($"{Response.StatusCode} Asset Image request failed\nError: {Response.ErrorMessage}");
                              }

            JArray Data = JObject.Parse(Response.Content)?["data"]?.Value<JArray>();

            if (Data != null && Data.Count > 0)
                return Data[0]?["imageUrl"]?.Value<string>();

            return "UNK";
        }
    }
}